image:
- Ubuntu1804

stack: python 3

environment:
  PY_DIR: C:\Python37-x64

clone_depth: 25

build: off

init:
- cmd: set PATH=%PY_DIR%;%PY_DIR%\Scripts;%PATH%
- sh: sudo apt install -yq --no-install-recommends ninja-build
- cmd: cinst -y ninja

install:
# had to pip here since stack: python 3 didn't take effect in init:
- pip install meson
- meson setup build

test_script: meson test -C build
