language: cpp
group: travis_latest
dist: bionic

git:
  depth: 25
  quiet: true

matrix:
  include:
  - os: linux
  - os: osx
    before_install: brew upgrade cmake
  - os: windows
    install:
    - cd build
    - cmake -G "MinGW Makefiles" -DCMAKE_SH="CMAKE_SH-NOTFOUND" ..
    - cmake --build . --parallel

install:
- cd build
- cmake ..
- cmake --build . --parallel

script: ctest -V
