language: cpp
group: travis_latest
dist: xenial

git:
  depth: 25
  quiet: true

matrix:
  include:
  - os: linux
  - os: osx
  - os: windows
    install:
    - cd build
    - cmake -G "MinGW Makefiles" -DCMAKE_SH="CMAKE_SH-NOTFOUND" ..
    - cmake --build . -j
    script: echo 4 | 2048.exe

install:
- cd build
- cmake ..
- cmake --build . -j

script:
- ctest --output-on-failure
